store_1/store_1/urls.py
from django.contrib import admin
from django.urls import path

from products.views import index, products

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index, name='index'),
    path("products", products, name='products'),
]

store_1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from rest_framework_simplejwt.views import (TokenObtainPairView,
                                            TokenRefreshView, TokenVerifyView)

from orders.views import stripe_webhook_view
from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('api/v1/', include('api.api_v1.urls', namespace='api_v1')),
    path('api/v1/drf-auth/', include('rest_framework.urls')),
    path('api/v1/auth/', include('djoser.urls')),
    path('api/v1/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    re_path(r'^auth/', include('djoser.urls.authtoken')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import (EmailVerificationView, LoginView, ProfileEditView,
                         ProfileView, RegisterView)

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', ProfileEditView.as_view(), name='profile_edit'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='emailverification'),
]

users/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.db import models
from django.urls import reverse
from django.utils.timezone import now


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', default='users_images/default_avatar.jpg')
    email = models.EmailField(('email address'), blank=True, unique=True)
    is_verified_email = models.BooleanField(default=False)
    
    class Meta:
        ordering = ('id',)


class EmailVerification(models.Model):
    code = models.UUIDField(unique=True)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    expiration = models.DateTimeField()
    
    def __str__(self):
        return f'EmailVerification object for {self.user.email}'

    def send_verification_email(self):
        link = reverse('users:emailverification', args=(self.user.email, self.code))
        verificationlink = settings.DOMAIN_NAME + link
        subject = f'Подтверждение учетной записи для {self.user.username}'
        message = f'Для подтверждения почты {self.user.email} '\
                  f'перейдите по ссылке {verificationlink}'
        send_mail(subject, message, settings.EMAIL_HOST_USER, 
                  [self.user.email], fail_silently=False)

    def is_expired(self):
        return True if now() <= self.expiration else False

users/forms.py
from django import forms
from django.contrib.auth.forms import (AuthenticationForm, UserChangeForm,
                                       UserCreationForm)

from users.models import User
from users.tasks import send_email_verify


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 
        'placeholder': 'Введите имя пользователя',
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 
        'placeholder': 'Введите пароль',
    }))
    
    class Meta:
        model = User
        fields = ('username', 'password')


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 
        'placeholder': 'Введите имя',
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 
        'placeholder': 'Введите фамилию',
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 
        'placeholder': 'Введите имя пользователя',
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4', 
        'placeholder': 'Введите адрес эл. почты',
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 
        'placeholder': 'Введите пароль',
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 
        'placeholder': 'Подтвердите пароль',
    }))
    
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 
                  'email', 'password1', 'password2')
        
    def save(self, commit=True):
        user = super().save(commit)
        send_email_verify.delay(user.id)
        
        return user
    

class ProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 
    }))
    image = forms.ImageField(widget=forms.FileInput(attrs={
        'class': 'form-control-custom',
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4', 
        'readonly': True,
    }))
    
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 
                  'image', 'username', 'email')

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import (CreateView, DetailView, TemplateView,
                                  UpdateView)

from common.views import CommonContextMixin, ReverseProfileMixin
from users.forms import LoginForm, ProfileForm, RegisterForm
from users.models import EmailVerification, User


class LoginView(ReverseProfileMixin, CommonContextMixin, LoginView):
    template_name = 'users/login.html'
    form_class = LoginForm
    title = 'Store - Авторизация'


class RegisterView(CommonContextMixin, SuccessMessageMixin, CreateView):
    model = User
    form_class = RegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')
    success_message = 'Регистрация прошла успешно!'
    title = 'Store - Регистрация'


class ProfileView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'users/profile.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = f'{self.object.id} - {self.object}'
        
        return context


class ProfileEditView(ReverseProfileMixin, SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    """
    Контроллер редактирования прфоиля
    """
    template_name = 'users/profile_edit.html'    
    form_class = ProfileForm
    model = User
    success_message = 'Профиль изменен!'

    def get_object(self, queryset=None):
        return self.request.user


class EmailVerificationView(CommonContextMixin, TemplateView):
    template_name = 'users/email_verification.html'
    title = 'Store - Подтверждение электронной почты'

    def get(self, request, *args, **kwargs):
        code = kwargs['code']
        user = User.objects.get(email=kwargs['email'])
        emailverifications = EmailVerification.objects.filter(user=user,
                                                              code=code)
        if emailverifications.exists() and emailverifications.first().is_expired():
            user.is_verified_email = True
            user.save()
            return super().get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('index'))

users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ title }}</title>
    <link href="{% static 'vendor/css/auth.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        {% block content %}  {% endblock content %}
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'vendor/js/auth-admin.js' %}"></script>
</body>
</html>

users/templates/users/email_verification.html
{% extends 'users/base.html' %}

{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header"><h3 class="text-center font-weight-light my-4">Поздравляем</h3>
                        </div>
                        <div class="card-body text-center">
                            <h4>Ваша учетная запись успешно подтверждена!</h4>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small"><a href="{% url 'index' %}">Продолжить</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

users/templates/users/form_errors.html
{% if messages or form.errors or error or form.non_field_errors %}
<div class="container mt-2">
    <div class="alert alert-
    {% if messages %}
        alert-success
    {% else %}
        alert-danger
    {% endif %} text-center" role="alert">
    {% if messages %}
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    {% elif form.non_field_errors %}
        {{ form.non_field_errors }}
    {% elif form.errors %}
        {{ form.errors }}
    {% elif form.non_field_errors%}
        {{ form.non_field_errors }}
    {% endif %}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
</div>
{% endif %}

users/templates/users/login.html
{% extends 'users/base.html' %}

{% load socialaccount %}

{% block content %}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                {% if messages or form.non_field_errors %}
                    <div class="alert 
                    {% if messages %}
                        alert-success
                    {% else %}
                        alert-danger
                    {% endif %}
                    alert-dismissible fade show" role="alert"
                        style="margin-top: 50px;">
                        {% if messages %}
                            {% for message in messages %}
                                {{ message }}
                            {% endfor %}
                        {% else %}
                            {{ form.non_field_errors }}
                        {% endif %}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
                    </div>
                    <div class="card-body">
                        <form action="{% url 'users:login' %}" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                                {{ form.username }}
                            </div>
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.password.id_for_label }}">Пароль</label>
                                {{ form.password }}
                            </div>
                            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                <a class="small" href="#">Забыли пароль?</a>
                                <input class="btn btn-primary" type="submit" value="Авторизоваться">
                            </div>
                            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                             
                            </div>
                        </form>
                    </div>
                    <div class="card-footer text-center">
                        <div class="small"><a href="{% url 'users:register' %}">Нужен аккаунт? Зарегистрируйся!</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

users/templates/users/profile.html
{% extends 'products/base.html' %}

{% load static %}

{% load humanize %}

{% block css %} 
<link href="{% static 'vendor/css/profile.css' %}" rel="stylesheet"> 
{% endblock css %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-7">
            <h4 class="mt-3 mb-3">Профиль</h4>
            <div class="col-lg-12 text-center">
                {% include 'users/form_errors.html' %}
                <img width="100" height="100"
                    src="
                    {% if user.image %} 
                        {{ user.image.url}} 
                    {% else %} 
                        {% static 'vendor/img/users/default_avatar.jpg' %}
                    {% endif %}"
                    class="img-thumbnail">
            </div>
            <div class="container_cont">
                <ul class="list-group mt-5">
                    <li class="list-group-item bg-dark-1">Имя пользователя: {{ object }}</li>
                    {% if object == request.user %}<li class="list-group-item bg-dark-1">Почта: {{ object.email }}</li>{% endif %}
                    {% if object.first_name %}<li class="list-group-item bg-dark-1">Имя и фамилия: {{ object.first_name }}</li>{% endif %}
                    {% if object.last_name %}<li class="list-group-item bg-dark-1">Фамилия: {{ object.last_name }}</li>{% endif %} 
                    {% if object.birth_day %}<li class="list-group-item bg-dark-1">Родился(ась) {{ object.birth_day }}</li>{% endif %}
                    {% if object.last_login %}<li class="list-group-item bg-dark-1">
                        Заходил(a) {{ object.last_login|naturaltime }}
                    </li>{% endif %} 
                    <li class="list-group-item bg-dark-1">Дата регистрации: {{ object.date_joined }}</li>                    
                </ul>
                {% if request.user == object %}
                    <a href="{% url 'users:profile_edit' %}" class="btn btn-sm btn-outline-dark mt-2">
                        Редактировать профиль
                    </a>
                {% endif %}
            </div>
        </div>
        <div class="col-lg-5">
            {% if object == request.user %} {% include 'products/basket.html' %} {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/profile_edit.html
{% extends 'products/base.html' %}

{% load static %}

{% load humanize %}

{% block css %} 
<link href="{% static 'vendor/css/profile.css' %}?123" rel="stylesheet"> 
{% endblock css %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-7">
            <h4 class="mt-3 mb-3">Профиль</h4>
            <div class="col-lg-12 text-center">
                {% include 'users/form_errors.html' %}
                <img width="100" height="100"
                    src="
                    {% if user.image %} 
                        {{ user.image.url}} 
                    {% else %} 
                        {% static 'vendor/img/users/default_avatar.jpg' %}
                    {% endif %}"
                    class="img-thumbnail">
            </div>
            <div class="container_cont">
                <form action="{% url 'users:profile_edit' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row mt-2">
                        <div class="col-md-6"><label class="labels">Имя пользователя:</label>
                            {{ form.username }}
                        </div>
                    </div>
                    <div class="row mt-2">
                        <div class="col-md-6"><label class="labels">Имя:</label>
                            {{ form.first_name }}
                        </div>
                        <div class="col-md-6"><label class="labels">Фамилия:</label>
                            {{ form.last_name }}
                        </div>
                    </div>
                    <div class="row mt-2">
                        <div class="col-md-6"><label class="labels">Почта:</label>
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="mt-3">
                        <label for="formFile" class="form-label">Аватар</label>
                        {{ form.image }}
                    </div>
                    <div class="mt-5 text-center">
                        <button class="btn btn-outline-dark mb-5" type="subbmit">
                            Сохранить профиль
                        </button>
                    </div>
                </form>               
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/register.html
{% extends 'users/base.html' %}

{% block content %}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-7">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert"
                        style="margin-top: 50px;">
                        {{ form.errors }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
                    </div>
                    <div class="card-body">
                        <form action="{% url 'users:register' %}" method="POST">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                        {{ form.first_name }}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                        {{ form.last_name }}
                                    </div>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-md-6">
                                    <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                                    {{ form.username }}
                                </div>
                                <div class="col-md-6">
                                    <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                        почты</label>
                                    {{ form.email }}
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
                                        {{ form.password1 }}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.password2.id_for_label }}">Подтверждение
                                            пароля</label>
                                        {{ form.password2 }}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group mt-4 mb-0">
                                <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                            </div>
                        </form>
                    </div>
                    <div class="card-footer text-center">
                        <div class="small"><a href="{% url 'users:login' %}">Уже есть аккаунт? Авторизоваться</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}