orders/urls.py
from django.urls import path

from orders.views import (CancelTemplateView, OrderCreateView, OrderDetailView,
                          OrderListView, SuccessTemplateView)

app_name = 'orders'

urlpatterns = [
    path('create/', OrderCreateView.as_view(), name='create'),
    path('success/', SuccessTemplateView.as_view(), name='success'),
    path('cancel/', CancelTemplateView.as_view(), name='cancel'),
    path('', OrderListView.as_view(), name='orders_list'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order'),
]

products/urls.py
from django.urls import path

from products.views import (ProductsListView, basket_add, basket_remove,
                            basket_remove_one_item)

app_name = 'products'

urlpatterns = [
    path('', ProductsListView.as_view(), name='index'),
    path('category/<int:category_id>/', ProductsListView.as_view(), name='category'),
    path('page/<int:page>/', ProductsListView.as_view(), name='paginator'),
    path('basket/add/<int:product_id>/', basket_add, name='basket_add'),
    path('basket/remove/<int:basket_id>/', basket_remove, name='basket_remove'),
    path('basket/remove_one_item/<int:product_id>/', basket_remove_one_item, name='basket_remove_one_item'),
]

store_1/store_1/urls.py
from django.contrib import admin
from django.urls import path

from products.views import index, products

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index, name='index'),
    path("products", products, name='products'),
]

store_1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from rest_framework_simplejwt.views import (TokenObtainPairView,
                                            TokenRefreshView, TokenVerifyView)

from orders.views import stripe_webhook_view
from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('api/v1/', include('api.api_v1.urls', namespace='api_v1')),
    path('api/v1/drf-auth/', include('rest_framework.urls')),
    path('api/v1/auth/', include('djoser.urls')),
    path('api/v1/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    re_path(r'^auth/', include('djoser.urls.authtoken')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import (EmailVerificationView, LoginView, ProfileEditView,
                         ProfileView, RegisterView)

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', ProfileEditView.as_view(), name='profile_edit'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='emailverification'),
]

products/models.py
import stripe
from django.conf import settings
from django.db import models

from users.models import User

stripe.api_key = settings.STRIPE_SECRET_KEY


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = 'категорию'
        verbose_name_plural = 'Категории'
        
    def __str__(self):
        return self.name
    
    
class Product(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField()
    price = models.DecimalField(max_digits=7, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='products_images', blank=True)
    category = models.ForeignKey(to=ProductCategory, on_delete=models.PROTECT)
    stripe_product_price_id = models.CharField(max_length=128, null=True, blank=True)

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'Продукты'
        ordering = ('id',)
        
    def __str__(self):
        return f'Продукт - {self.name} | Категория - {self.category.name}'
    
    def save(self, *args, **kwargs):
        if not self.stripe_product_price_id:
            stripe_product_price = self.create_stripe_product_price()
            self.stripe_product_price_id = stripe_product_price['id']
            
        super().save(*args, **kwargs)
    
    def create_stripe_product_price(self):
        stripe_product = stripe.Product.create(name=self.name)
        stripe_product_price = stripe.Price.create(
            product=stripe_product, 
            unit_amount=round(self.price * 100), 
            currency="rub"
        )
        
        return stripe_product_price


class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(bsk.sum() for bsk in self)
    
    def total_quantity(self):
        return sum(bsk.quantity for bsk in self)

    def stripe_products(self):
        line_items = []
        for i in self:
            item = {
                'price': i.product.stripe_product_price_id,
                'quantity': i.quantity,
            }
            line_items.append(item)
            
        return line_items


class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    objects = BasketQuerySet.as_manager()
    
    class Meta:
        verbose_name = 'корзину'
        verbose_name_plural = 'корзина'
        
    def __str__(self):
        return f"Корзина для {self.user.username, self.user.id} | Продукт: {self.product.name}"

    def sum(self):
        return self.product.price * self.quantity

    def de_json(self):
        basket_item = {
            'prod_name': self.product.name,
            'quantity': self.quantity,
            'price': float(self.product.price),
            'sum': float(self.sum()),
        }
        
        return basket_item

store_1/products/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name
    

class Product(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField()
    price = models.DecimalField(max_digits=7, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='products_images')
    category = models.ForeignKey(to=ProductCategory, on_delete=models.PROTECT)

products/views.py
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.shortcuts import HttpResponseRedirect
from django.views.generic import ListView, TemplateView

from common.views import CommonContextMixin
from products.models import Basket, Product, ProductCategory


class IndexView(CommonContextMixin, TemplateView):
    template_name = 'products/index.html'
    title = 'Store'


class ProductsListView(CommonContextMixin, ListView):
    model = Product
    template_name = 'products/products.html'
    paginate_by = 3
    title = 'Store - Каталог'
    
    def get_queryset(self):
        queryset = cache.get('queryset')
        if not queryset:
            queryset = super().get_queryset()
            cache.set('queryset', queryset, 30)
            
        category_id = self.kwargs.get('category_id')
        
        return queryset.filter(category_id=category_id) if category_id else queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = ProductCategory.objects.all()

        return context


@login_required
def basket_add(request, product_id):
    basket = Basket.objects.filter(user=request.user, product_id=product_id)
    if not basket.exists():
        Basket.objects.create(user=request.user, product_id=product_id, quantity=1)
    else:
        bsk = basket[0]
        bsk.quantity += 1
        bsk.save()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def basket_remove_one_item(request, product_id):
    basket = Basket.objects.get(user=request.user, product_id=product_id)
    if basket.quantity == 1:
        basket.delete()
    else:
        basket.quantity -= 1
        basket.save()
        
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

products/templates/products/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet" />

    <!-- Custom styles for this template -->
    {% block css %} {% endblock css %}
</head>

<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{% url 'index' %}">Store</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'products:index' %}">Каталог <i
                                class="fas fa-shopping-bag"></i>
                        </a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fas fa-user-circle"></i>
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>
                                    <a class="dropdown-item" href="{% url 'users:profile' request.user.id%}">Профиль</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'orders:orders_list' %}">Заказы</a>
                                </li>
                                {% if request.user.is_superuser or request.user.is_staff %}
                                    <li>
                                        <a class="dropdown-item" href="{% url 'admin:index' %}">Админ-панель</a>
                                    </li>
                                {% endif %}
                                <li>
                                    <hr class="dropdown-divider" />
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'users:logout' %}">
                                        Выйти
                                    </a>
                                </li>
                            </ul>
                        </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <!-- Page Content -->
    {% block content %} {% endblock content %}

    {% block footer %} {% endblock footer %}

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js'%}"></script>
    <script src="{% static 'vendor/bootstrap/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

    <!-- FontAwesome script -->
    <script src="{% static 'vendor/fontawesome/fontawesome-icons.js'%}" crossorigin="anonymous"></script>
</body>

</html>

products/templates/products/basket.html
{% load humanize %}

{% if basket %}
    <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
        Корзина <span class="badge badge-secondary badge-pill">{{ basket.total_quantity }}</span>
    </h4>
    {% for bsk in basket %}
        <div class="card mb-3">
            <div class="card-body">
                <h5 class="card-title">{{ bsk.product.name }}</h5>
                <p class="card-text">{{ bsk.product.description }}</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item bg-light">
                    <div class="row text-center">
                        <div class="col-lg-4">
                            <input name="basketID" type="number" class="form-control"
                                value="{{ bsk.quantity }}" min="0" disabled>
                            <div class="row">
                                <div class="col-lg-6">
                                    <a href="{% url 'products:basket_add' bsk.product.id %}">
                                        <span style="font-size: 1.5em;">+</span>
                                    </a>
                                </div>
                                <div class="col-lg-6">
                                    <a href="{% url 'products:basket_remove_one_item' bsk.product.id %}">
                                        <span style="font-size: 1.5em;">-</span>
                                    </a>
                                </div>
                            </div>
                        </div>  
                        <div class="col-lg-4"> {{ bsk.sum|intcomma }} руб.</div>
                        <div class="col-lg-4">
                            <a href="{% url 'products:basket_remove' bsk.id %}">
                                <i class="fas fa-trash"></i>
                            </a>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    {% endfor %}
    <div class="card mb-3">
        <div class="card-footer">
            <p class="float-left">Итого</p>
            <h4 class="float-right">{{ basket.total_sum|intcomma }} руб.</h4>
        </div>
    </div>
    <a class="btn btn-success btn-lg float-right" href="{% url 'orders:create' %}">
        Оформить заказ
    </a>
{% else %}
    <h4 class="mt-3 mb-3 text-center">
        Корзина пуста
    </h4>
{% endif %}

products/templates/products/index.html
{% extends 'products/base.html' %}

{% load static %}

{% block css %}
<link href="{% static 'vendor/css/index.css'%}" rel="stylesheet" /> 
{% endblock css %}

{% block content %}
<section>
    {% comment %}
    <div class="alert alert-light text-center" role="alert">
        Информационное сообщение
    </div>
    {% endcomment %}
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">Store</h1>
                <p>
                    Новые образы и лучшие бренды на Store. Бесплатная доставка
                    по всему миру! Аутлет: до -70% Собственный бренд. -20% новым
                    покупателям.
                </p>
                <a id="start-purchase-link" href="{% url 'products:index' %}">
                    <button id="start-purchase-btn" type="button" class="btn btn-lg">

                        Начать покупки

                    </button>
                </a>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

products/templates/products/products.html
{% extends 'products/base.html' %}

{% load humanize %}

{% load static cache %}

{% block css %} <link href="{% static 'vendor/css/products.css'%}" rel="stylesheet" /> {% endblock css %}

{% block content %} 
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <h1 class="my-4">Store</h1>
                <div class="list-group">
                    <a href="{% url 'products:index' %}" class="list-group-item">Все</a>
                    {% for cat in categories%}
                        <a href="{% url 'products:category' cat.id %}" class="list-group-item">{{ cat.name }}</a>
                    {% endfor %}
                </div>
            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">
                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-1.jpg"
                                alt="First slide" />
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-2.jpg"
                                alt="Second slide" />
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-3.jpg"
                                alt="Third slide" />
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <div class="row">
                    {% for prod in object_list %}
                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card h-100">
                            <a href="#">
                                {% if prod.image %}<img class="card-img-top" src="{{ prod.image.url }}" alt="" />{% endif %}
                            </a>
                            <div class="card-body">
                                <h4 class="card-title">
                                    <a href="#">{{ prod.name }}</a>
                                </h4>
                                <h5>{{ prod.price|intcomma }}</h5>
                                <p class="card-text">
                                    {{ prod.description }}
                                </p>
                            </div>
                            <div class="card-footer text-center">
                                <a href="{% url 'products:basket_add' prod.id %}">
                                    <button type="button" class="btn btn-outline-success">
                                        Отправить в корзину
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% if is_paginated %}
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center">
                            <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                                <a class="page-link" 
                                href="
                                {% if page_obj.has_previous %} 
                                        {% url 'products:paginator' page_obj.previous_page_number %}
                                {% else %}
                                        #
                                {% endif %}"
                                tabindex="-1" 
                                aria-disabled="true">
                                Previous
                                </a>
                            </li>
                            {% for page in paginator.page_range %}
                                <li class="page-item 
                                {% if page == page_obj.number %}
                                    disabled
                                {% endif %}">
                                    <a class="page-link" href="{% url 'products:paginator' page %}">{{ page }}</a>
                                </li>
                            {% endfor %}
                            <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                                <a class="page-link" 
                                href="
                                {% if page_obj.has_next %} 
                                        {% url 'products:paginator' page_obj.next_page_number %} 
                                {% else %} 
                                        # 
                                {% endif %}">
                                Next
                                </a>
                            </li>
                        </ul>
                    </nav>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %} 

{% block footer %} 
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">
                Copyright &copy; Store 2022
            </p>
        </div>
    </footer>
{% endblock footer %}